# Generated by Django 4.2.16 on 2025-03-01 11:32

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('has_disabled_parking', models.BooleanField(default=False)),
                ('is_covered', models.BooleanField(default=False)),
                ('has_security_cameras', models.BooleanField(default=False)),
                ('has_security_guard', models.BooleanField(default=False)),
                ('payment_method', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slot_capacity', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('subcity', models.CharField(choices=[('Addis Ketema', 'Addis Ketema'), ('Akaky Kaliti', 'Akaky Kaliti'), ('Arada', 'Arada'), ('Bole', 'Bole'), ('Gullele', 'Gullele'), ('Kirkos', 'Kirkos'), ('Kolfe Keranio', 'Kolfe Keranio'), ('Lideta', 'Lideta'), ('Nifas Silk-Lafto', 'Nifas Silk-Lafto'), ('Yeka', 'Yeka')], max_length=60)),
                ('woreda', models.IntegerField()),
                ('keble', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='parking_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='parking_images')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcity', models.CharField(choices=[('Addis Ketema', 'Addis Ketema'), ('Akaky Kaliti', 'Akaky Kaliti'), ('Arada', 'Arada'), ('Bole', 'Bole'), ('Gullele', 'Gullele'), ('Kirkos', 'Kirkos'), ('Kolfe Keranio', 'Kolfe Keranio'), ('Lideta', 'Lideta'), ('Nifas Silk-Lafto', 'Nifas Silk-Lafto'), ('Yeka', 'Yeka')], max_length=20)),
                ('woreda', models.CharField(max_length=20)),
                ('kebele', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLegalDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_file', models.FileField(upload_to='ParkingLegalDoc/insurance_file')),
                ('legal_document', models.FileField(upload_to='ParkingLegalDoc/legal_file')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='parking_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinggroup'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('private', 'private'), ('public', 'public')], max_length=30)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
            ],
        ),
    ]
