# Generated by Django 4.2.16 on 2025-03-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
