# Generated by Django 4.2.16 on 2025-03-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserveparking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveparking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserveparking',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
