# Generated by Django 4.2.16 on 2025-03-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platenumber',
            name='plate_number',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
